{% set name = "montreal-forced-aligner" %}
{% set version = "2.0.0b11" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Montreal Forced Aligner-{{ version }}.tar.gz
  sha256: 32d03b0af779edd058a5078fa18d6958649178781bee485524cd4fff80653974

build:
  number: 1
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - mfa = montreal_forced_aligner.command_line.mfa:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - setuptools
    - setuptools_scm
    - wheel
    - python
    - pip
    - kaldi
    - sox
    - openfst  # [not win and build_platform == target_platform]
    - baumwelch  # [not win and build_platform == target_platform]
    - ngram  # [not win and build_platform == target_platform]
    - pynini  # [not win and build_platform == target_platform]
    - librosa
    - tqdm
    - requests
    - colorama
    - ansiwrap
    - pyyaml
    - jsonlines
    - biopython
    - praatio
  run:
    - python
    - kaldi
    - pynini  # [not win and build_platform == target_platform]
    - openfst  # [not win and build_platform == target_platform]
    - baumwelch  # [not win and build_platform == target_platform]
    - ngram  # [not win and build_platform == target_platform]
    - sox
    - librosa
    - tqdm
    - requests
    - colorama
    - ansiwrap
    - pyyaml
    - biopython
    - jsonlines
    - praatio

test:
  imports:
    - montreal_forced_aligner
    - montreal_forced_aligner.acoustic_modeling
    - montreal_forced_aligner.alignment
    - montreal_forced_aligner.command_line
    - montreal_forced_aligner.corpus
    - montreal_forced_aligner.dictionary
    - montreal_forced_aligner.g2p
    - montreal_forced_aligner.ivector
    - montreal_forced_aligner.language_modeling
    - montreal_forced_aligner.transcription
    - montreal_forced_aligner._version
    - montreal_forced_aligner.abc
    - montreal_forced_aligner.config
    - montreal_forced_aligner.data
    - montreal_forced_aligner.exceptions
    - montreal_forced_aligner.helper
    - montreal_forced_aligner.models
    - montreal_forced_aligner.segmenter
    - montreal_forced_aligner.speaker_classifier
    - montreal_forced_aligner.textgrid
    - montreal_forced_aligner.utils
    - montreal_forced_aligner.validator

about:
  home: https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Forced aligner for speech to text alignment
  description: |
    The Montreal Forced Aligner is a command line utility for performing forced alignment of speech datasets using
    Kaldi <http://kaldi-asr.org/>.
  doc_url: https://montreal-forced-aligner.readthedocs.io/
  dev_url: https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner

extra:
  recipe-maintainers:
    - mmcauliffe
