{% set name = "montreal-forced-aligner" %}
{% set version = "3.0.6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name | replace("-", "_") }}/Montreal_Forced_Aligner-{{ version }}.tar.gz
  sha256: 2eac0703e342cc7501bbd1bc240390bd9dfc71d0f9ebd9d1f66569ee8e43c097

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - mfa = montreal_forced_aligner.command_line.mfa:mfa_cli
  run_exports:
    - {{ pin_subpackage('montreal-forced-aligner', max_pin='x.x.x') }}

requirements:
  host:
    - setuptools
    - setuptools_scm
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - kaldi
    - pynini
    - openfst
    - baumwelch
    - ngram
    - sox
    - ffmpeg
    - librosa
    - pysoundfile
    - numpy
    - tqdm
    - requests
    - pyyaml
    - biopython =1.79
    - praatio =6.0.0
    - sqlalchemy >=2.0
    - dataclassy
    - numba
    - kneed
    - pgvector
    - pgvector-python
    - postgresql
    - sqlite
    - hdbscan
    - psycopg2
    - scikit-learn <1.3
    - rich
    - rich-click
    - kalpy =0.6.4=cpu*
  run_constrained:
    - kalpy

test:
  commands:
    - mfa --help
    - mfa_update
  imports:
    - montreal_forced_aligner
    - montreal_forced_aligner.acoustic_modeling
    - montreal_forced_aligner.alignment
    - montreal_forced_aligner.command_line
    - montreal_forced_aligner.corpus
    - montreal_forced_aligner.diarization
    - montreal_forced_aligner.dictionary
    - montreal_forced_aligner.g2p
    - montreal_forced_aligner.ivector
    - montreal_forced_aligner.language_modeling
    - montreal_forced_aligner.online
    - montreal_forced_aligner.transcription
    - montreal_forced_aligner.vad
    - montreal_forced_aligner.validation
    - montreal_forced_aligner._version
    - montreal_forced_aligner.abc
    - montreal_forced_aligner.config
    - montreal_forced_aligner.data
    - montreal_forced_aligner.exceptions
    - montreal_forced_aligner.helper
    - montreal_forced_aligner.models
    - montreal_forced_aligner.textgrid
    - montreal_forced_aligner.utils

about:
  home: https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Forced aligner for speech to text alignment
  description: |
    The Montreal Forced Aligner is a command line utility for performing forced alignment of speech datasets using
    Kaldi <http://kaldi-asr.org/>.
  doc_url: https://montreal-forced-aligner.readthedocs.io/
  dev_url: https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner

extra:
  recipe-maintainers:
    - mmcauliffe
